services:
  app:
    build: .
    container_name: 49ja_game
    restart: always
    ports:
      - "5000:5000"
    shm_size: "1gb" # Crucial for preventing Firefox tab crashes
    volumes:
      - ./game_data.db:/app/game_data.db:z
      - ./app.log:/app/app.log:z
    environment:
      - DB_URL=sqlite:///game_data.db
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  caddy:
    image: caddy:2.11.4
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./conf:/etc/caddy
      - ./site:/static
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
